# This docker-compose file defines the development environment
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3.5"
services:
    hqregistrypostgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5430:5432"
        networks:
            - satwebspanet
    hqmiridpostgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5431:5432"
        networks:
            - satwebspanet
    hqregistry:
        image: identifiersorg/cloud-hq-ws-registry
        environment:
            - HQ_WS_REGISTRY_CONFIG_JDBC_URL=jdbc:postgresql://hqregistrypostgresql:5432/devdatabase
            - HQ_WS_REGISTRY_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_REGISTRY_CONFIG_RDBMS_PASSWORD=devpassword
            - HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_HOST=hqmiridcontroller
            - HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_PORT=8181
            - HQ_WS_REGISTRY_CONFIG_APPLICATION_ACTIVE_PROFILE=development,authdisabled
        ports:
            - "8180:8180"
        networks:
            - satwebspanet
        depends_on:
            - hqregistrypostgresql
            - hqmiridcontroller
    hqmiridcontroller:
        image: identifiersorg/cloud-hq-ws-mirid-controller
        environment:
            - HQ_WS_MIRID_CONTROLLER_CONFIG_JDBC_URL=jdbc:postgresql://hqmiridpostgresql:5432/devdatabase
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_PASSWORD:devpassword
            - HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_HOST=redis
            - HQ_WS_MIRID_CONTROLLER_CONFIG_APPLICATION_ACTIVE_PROFILE=development,authdisabled
        ports:
            - "8181:8181"
        networks:
            - satwebspanet
        depends_on:
            - redis
            - hqmiridpostgresql
    resolver:
        image: identifiersorg/cloud-ws-resolver
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=recommender
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
            - WS_RESOLVER_JVM_MEMORY_MAX=1024m
        ports:
            - "8080:8080"
        networks:
            - satwebspanet
        depends_on:
            - redis
            - recommender
    recommender:
        image: identifiersorg/cloud-ws-resource-recommender
        environment:
            - WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX=1024m
            - WS_RESOURCE_RECOMMENDER_CONFIG_BACKEND_SERVICE_LINK_CHECKER_HOST=link-checker
        ports:
            - "8083:8083"
        networks:
            - satwebspanet
        depends_on:
            - link-checker
    link-checker:
        image: identifiersorg/cloud-ws-link-checker
        environment:
            - WS_LINK_CHECKER_CONFIG_REDIS_HOST=redis
            - WS_LINK_CHECKER_CONFIG_BACKEND_SERVICE_RESOLVER_HOST=resolver
            - WS_LINK_CHECKER_CONFIG_DAEMON_PERIODIC_LINK_CHECK_REQUESTER_ENABLED=false
        ports:
            - "8084:8084"
        networks:
            - satwebspanet
        depends_on:
            - redis
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
        networks:
            - satwebspanet
networks:
    default:
        name: satwebspanet
    satwebspanet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.252.0/24
